### PR TITLE
Clean up of Inference Overhaul

### PR DESCRIPTION
**Pull request by EthanMarx**
@alecgunny Tagging you since I know you don't get notifications.

Using this PR to do some basic repository clean up / management with new changes.

### CODE REVIEW

**Comment by alecgunny** [comment]
@EthanMarx this is great appreciate it. Do you want me to merge or do you want to keep this as a running branch for fixes you find while reviewing?

**Comment by EthanMarx** [comment]
@alecgunny Was thinking running fixes. Some of the ledger tests were failing. Is there maybe a commit missing?

**Comment by alecgunny** [comment]
No if tests are breaking it's just because I had to update the API to get the pipeline running but didn't update the test. Feel free to take a look if you want to get more familiar with the API but I can also handle those cuz there's probably quite a few little gotchas

**Comment by EthanMarx** [comment]
I'm happy to give fixing them up a go

**Pull request merged**
